name: Get Pull Request
description: Find a pull request with a Jira issue key
branding:
  icon: 'book-open'
  color: 'blue'
inputs:
  token:
    description: Github token
    required: true
  issuekey:
    description: Jira issue key
    required: true
  mergeIn:
    description: Target Branch
  mergePull:
    description: Set it to true if willing to merge the PR and delete the headRef

runs:
  using: 'node12'
  main: './index.js'
