on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      issueKey:
        description: 'Jira issue key associated to Pull Request'
        required: true
      transitionName:
        description: 'Jira transition name'
        default: 'EN COURS'
      mergeIn:
        description: 'The branch where the Pull Request should be merged'
      mergePull:
        description: 'Set it to true if willing to merge the PR and delete the headRef'

jobs:
  jira_workflow:
    runs-on: ubuntu-latest
    name: Jira workfow
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Custom action
        uses: ./
        id: findBranch
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issueKey: ${{ github.event.inputs.issueKey }}
          mergeIn: ${{ github.event.inputs.mergeIn }}
          mergePull: ${{ github.event.inputs.mergePull }}
      - name: Login
        uses: atlassian/gajira-login@master
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
      - name: Find in commit messages
        uses: atlassian/gajira-find-issue-key@master
        id: find
        with:
          string: ${{ github.event.inputs.issuekey }}
      - name: Transition issue
        uses: atlassian/gajira-transition@master
        with:
          issue: ${{ steps.find.outputs.issue }}
          transition: ${{ github.event.inputs.transitionName }}
