on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      issuekey:
        description: 'Jira issue key used also in Pull Request'
        required: true

jobs:
  jira_workflow:
    runs-on: ubuntu-latest
    name: Jira workfow
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login
        uses: atlassian/gajira-login@master
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
      - name: Get Jira issue
        uses: ./
        with:
          issuekey: ${{ github.event.inputs.issuekey }}
      - name: Get the output jira issue
        run: echo "${{ steps.hello.outputs.issue }}"
