on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      issuekey:
        description: 'Jira issue key used also in Pull Request'
        required: true


jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login
        uses: atlassian/gajira-login@master
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}

      - name: Get Jira issue
        uses: ./
        id: hello
        with:
          issuekey: ${{ github.event.inputs.issuekey }}
      # Use the output from the `hello` step
      - name: Get the output jira issue
        run: echo "${{ steps.hello.outputs.issue }}"
