on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      issuekey:
        description: 'Jira issue key used also in Pull Request'
        required: true

jobs:
  jira_workflow:
    runs-on: ubuntu-latest
    name: Jira workfow
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name:
        uses: ./
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      # - name: Login
      #   uses: atlassian/gajira-login@master
      #   env:
      #     JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
      #     JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
      #     JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
      # - name: Find in commit messages
      #   uses: atlassian/gajira-find-issue-key@master
      #   id: find
      #   with:
      #     string: ${{ github.event.inputs.issuekey }}
      # - name: Transition issue
      #   uses: atlassian/gajira-transition@master
      #   with:
      #     issue: ${{ steps.find.outputs.issue }}
      #     transition: "EN COURS"
